import { MantineClientProvider } from '@/providers/MantineClientProvider';
import { QueryClientProvider } from '@/providers/QueryClientProvider';
import '@/styles/globals.scss';
import { ColorSchemeScript } from '@mantine/core';
import '@mantine/core/styles.css';
import type { Metadata } from 'next';
import localFont from 'next/font/local';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-mantine-color-scheme="light">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${geistSans.variable}`}>
        <MantineClientProvider>
          <QueryClientProvider>{children}</QueryClientProvider>
        </MantineClientProvider>
      </body>
    </html>
  );
}
